---
abstract: 'Lucy query dialect'
author:
  - 'Peter Karman <karman@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Search-Query-Dialect-Lucy
no_index:
  directory:
    - t
    - inc
requires:
  Lucy: '0.001'
  LucyX::Search::NullTermQuery: '0.002'
  LucyX::Search::WildcardQuery: '0.01'
  Search::Query: '0.29001'
  Test::More: '0'
  perl: '5.008003'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Search-Query-Dialect-Lucy
  homepage: https://github.com/karpet/search-query-dialect-lucy-perl
  license: http://dev.perl.org/licenses/
  repository: https://github.com/karpet/search-query-dialect-lucy-perl
version: 0.190_01
